# Generated by Django 6.0.3 on 2026-03-07 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("running", "Идёт"),
                            ("finished", "Завершено"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Соревнование",
                "verbose_name_plural": "Соревнования",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.IntegerField(verbose_name="Номер раунда")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("active", "Активен"),
                            ("completed", "Завершён"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="wine_app.competition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Раунд",
                "verbose_name_plural": "Раунды",
                "ordering": ["round_number"],
                "unique_together": {("competition", "round_number")},
            },
        ),
        migrations.CreateModel(
            name="Wine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название вина"),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Страна")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="wines/",
                        verbose_name="Картинка",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядковый номер"),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wines",
                        to="wine_app.competition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вино",
                "verbose_name_plural": "Вина",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Pairing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "votes_wine1",
                    models.IntegerField(default=0, verbose_name="Голосов за вино 1"),
                ),
                (
                    "votes_wine2",
                    models.IntegerField(default=0, verbose_name="Голосов за вино 2"),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок в раунде"),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairings",
                        to="wine_app.round",
                    ),
                ),
                (
                    "wine1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairings_as_first",
                        to="wine_app.wine",
                    ),
                ),
                (
                    "wine2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairings_as_second",
                        to="wine_app.wine",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="won_pairings",
                        to="wine_app.wine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пара",
                "verbose_name_plural": "Пары",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cookie_id", models.CharField(max_length=64)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "pairing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="wine_app.pairing",
                    ),
                ),
                (
                    "wine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wine_app.wine"
                    ),
                ),
            ],
            options={
                "verbose_name": "Голос",
                "verbose_name_plural": "Голоса",
                "unique_together": {("pairing", "cookie_id")},
            },
        ),
    ]
