# Generated by Django 6.0.3 on 2026-03-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wine_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pairing",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает"),
                    ("active", "Активен"),
                    ("completed", "Завершён"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="wine",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="wine",
            name="grape_variety",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Сорт винограда"
            ),
        ),
        migrations.AddField(
            model_name="wine",
            name="vintage",
            field=models.CharField(blank=True, max_length=10, verbose_name="Винтаж"),
        ),
    ]
