# Generated by Django 6.0.3 on 2026-03-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "wine_app",
            "0002_pairing_status_wine_description_wine_grape_variety_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="participant_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Имя участника"
            ),
        ),
    ]
