# Generated by Django 6.0.3 on 2026-03-08 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wine_app", "0003_vote_participant_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pairing",
            name="wine2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pairings_as_second",
                to="wine_app.wine",
            ),
        ),
    ]
